### ISSUE TITLE
Null Prefix

### ISSUE THREAD

**Issue by SwordOfSouls** [joserodpt/RealRegions#1]
All chat messages are prefixed with "null"

**Comment by joserodpt** [comment]
Hi there! Thanks for reporting!
It appears to not be able to get the prefix in the config. Please check if below jar file fixes the issue. Thanks!
[RealRegions.jar.zip](https://github.com/joserodpt/RealRegions/files/12213497/RealRegions.jar.zip)

**Comment by joserodpt** [comment]
Closing the issue as solved.
