### ISSUE TITLE
Conflicts with Deluxe hub

### ISSUE THREAD

**Issue by SimpleWayx** [joserodpt/RealRegions#2]
I tried to manage game rules of the world but it always restarts with true on every game rules of the world in global. 

Seems that there is conflict between the game rules of the DeluxeHub when loading worlds outside from out of the ordinary worlds (Lobby in this case).

Is a great addition but is difficult to get this plugin to make it work with lobby plugins that change game rules as well.

**Comment by joserodpt** [comment]
Hi there, thanks for the report!
By game rules, are you referring to flags? 
Are there any errors in the console?

**Comment by joserodpt** [comment]
Fixed that issue in commit https://github.com/joserodpt/RealRegions/commit/804b26b0f148b709254d96ded52fb1bbb3b9d2ad, please test the below jar file, thanks!
[RealRegions.jar.zip](https://github.com/joserodpt/RealRegions/files/12227353/RealRegions.jar.zip)

**Comment by SimpleWayx** [comment]
Thanks for the quick response, It seems to work now they stay at a place in a global scale.

This may be related now to the Deluxehub plugin but still allows to drop items. I had to disable RR on the Lobby world in order to Deluxe hub concede the Flags for the world but still allow the Load "worlds" from RealRegions.

Thanks for the quick support.

**Comment by joserodpt** [comment]
Hi there, glad that it is fixed! :D
